const en = {
  moreMenu: 'More', shareAction: 'Share', tagline: 'A world of interests. Yours to connect.',
  copyHobby: 'Copy link to this hobby', copied: 'Hobby link copied.',
  explore: 'Explore', atlas: 'Atlas', mine: 'Your hobbies', directions: 'Choose a direction', all: 'All directions',
  eyebrow: 'A little curiosity goes a long way', headline: 'Follow what fascinates you.',
  intro: 'Find a hobby, explore its rabbit holes, and discover what connects the things you love.',
  search: 'Search hobbies, skills, or subtopics', searchHint: 'Try photography, baking, or worldbuilding',
  categories: 'Find your way in', categoryHint: 'Start with a family. There is plenty to explore inside.',
  allHobbies: 'All hobbies', easy: 'Easy to start', deep: 'With subtopics', results: 'results',
  hobbies: 'hobbies', subtopics: 'subtopics', more: 'Show more', browseAll: 'Browse all directions',
  save: 'Save hobby', saved: 'Saved', remove: 'Remove saved hobby', local: 'Saved in this browser. No account needed.',
  openMap: 'Open in atlas',
  first: 'Your first small experiment', deeper: 'Go a little deeper', deeperHint: 'Pick a direction that interests you. These are possibilities, not a checklist.',
  connections: 'See what connects', connectionsHint: 'The same interest, seen from four different angles.',
  related: 'Related hobbies', skills: 'Shared skills', gear: 'Shared gear', interests: 'Shared interests',
  relatedHint: 'Authored links to nearby pursuits and natural next steps.',
  skillsHint: 'Skills this hobby uses, and other pursuits that use them too.',
  gearHint: 'Authored connections where equipment or materials carry over.',
  interestsHint: 'Inferred from two or more shared tags. These are affinities, not equipment links.',
  through: 'Connected through', tags: 'Shared interests', showMap: 'See this connection on the atlas',
  noConnections: 'No connections recorded for this angle yet. Try another view.',
  noResults: 'No hobbies found this time.', noResultsHint: 'Try a broader word or clear the filters. Subtopics are searchable too.',
  reset: 'Clear search and filters', collectionTitle: 'Make room for what you love.',
  collectionIntro: 'Your hobbies, techniques, and the connections between them. A collection that grows with your curiosity.',
  emptyTitle: 'Your collection starts with one interest.', emptyHint: 'Save something you enjoy or want to explore. It will be waiting here next time.',
  start: 'Find a hobby', skill: 'Shared craft', back: 'Back to', inside: 'Inside', allCategories: 'All categories',
  unavailable: 'This part of the atlas is not here.', unavailableHint: 'The link may be incomplete. You can still explore all the hobby families.',
  partial: 'Some browse content could not load. Basic browsing still works; reload to retry.',
  treeError: 'The subtopics could not load.', retry: 'Try again', advanced: 'More ways to explore',
  commitment: 'How much space does it have in your life?', commitmentHint: 'Optional. Choose the time you give it, not a skill rating.',
  mapHelp: 'Want the big picture?', mapHint: 'Pan, zoom, and follow the paths between whole families of hobbies.',
  viewSummary: 'View your summary', share: 'Share collection', browse: 'Browse', techniques: 'Explore these subtopics',
  saveFeedback: 'Saved to your hobbies.', removeFeedback: 'Removed from your hobbies.',
};
const es = {
  moreMenu: 'Más', shareAction: 'Compartir', tagline: 'Un mundo de intereses. Conéctalos a tu manera.',
  copyHobby: 'Copiar enlace a esta afición', copied: 'Enlace copiado.',
  explore: 'Explorar', atlas: 'Atlas', mine: 'Tus aficiones', directions: 'Elige una dirección', all: 'Todas las direcciones',
  eyebrow: 'La curiosidad es un buen comienzo', headline: 'Sigue lo que te fascina.',
  intro: 'Encuentra una afición, profundiza en sus detalles y descubre qué conecta las cosas que te gustan.',
  search: 'Buscar aficiones, habilidades o subtemas', searchHint: 'Prueba fotografía, repostería o mundos de ficción',
  categories: 'Encuentra tu punto de partida', categoryHint: 'Empieza por una familia. Hay mucho por descubrir dentro.',
  allHobbies: 'Todas las aficiones', easy: 'Fáciles de empezar', deep: 'Con subtemas', results: 'resultados',
  hobbies: 'aficiones', subtopics: 'subtemas', more: 'Mostrar más', browseAll: 'Explorar todas las direcciones',
  save: 'Guardar afición', saved: 'Guardado', remove: 'Quitar afición guardada', local: 'Se guarda en este navegador. No necesitas una cuenta.',
  openMap: 'Abrir en el atlas',
  first: 'Tu primer pequeño experimento', deeper: 'Profundiza un poco más', deeperHint: 'Elige lo que te interese. Son posibilidades, no una lista de tareas.',
  connections: 'Descubre las conexiones', connectionsHint: 'El mismo interés, desde cuatro ángulos distintos.',
  related: 'Aficiones relacionadas', skills: 'Habilidades compartidas', gear: 'Equipo compartido', interests: 'Intereses compartidos',
  relatedHint: 'Conexiones descritas entre actividades cercanas y posibles próximos pasos.',
  skillsHint: 'Las habilidades que usa esta afición y otras actividades que también las usan.',
  gearHint: 'Conexiones descritas en las que se comparten equipos o materiales.',
  interestsHint: 'Inferidas a partir de dos o más etiquetas compartidas. Son afinidades, no conexiones de equipo.',
  through: 'Conexión a través de', tags: 'Intereses compartidos', showMap: 'Ver esta conexión en el atlas',
  noConnections: 'Todavía no hay conexiones registradas para este ángulo. Prueba otra vista.',
  noResults: 'Esta vez no encontramos aficiones.', noResultsHint: 'Prueba una palabra más general o quita los filtros. También puedes buscar subtemas.',
  reset: 'Borrar búsqueda y filtros', collectionTitle: 'Haz espacio para lo que te gusta.',
  collectionIntro: 'Tus aficiones, técnicas y las conexiones entre ellas. Una colección que crece con tu curiosidad.',
  emptyTitle: 'Tu colección empieza con un interés.', emptyHint: 'Guarda algo que disfrutes o quieras explorar. Te estará esperando aquí la próxima vez.',
  start: 'Encuentra una afición', skill: 'Habilidad compartida', back: 'Volver a', inside: 'Dentro de', allCategories: 'Todas las categorías',
  unavailable: 'Esta parte del atlas no está aquí.', unavailableHint: 'Puede que el enlace esté incompleto. Aún puedes explorar todas las familias.',
  partial: 'Parte del contenido no se pudo cargar. Puedes seguir explorando o recargar para reintentar.',
  treeError: 'No se pudieron cargar los subtemas.', retry: 'Reintentar', advanced: 'Más formas de explorar',
  commitment: '¿Cuánto espacio ocupa en tu vida?', commitmentHint: 'Opcional. Elige el tiempo que le dedicas, no tu nivel de habilidad.',
  mapHelp: '¿Quieres ver el panorama completo?', mapHint: 'Desplázate, acerca el mapa y sigue las conexiones entre familias de aficiones.',
  viewSummary: 'Ver tu resumen', share: 'Compartir colección', browse: 'Explorar', techniques: 'Explora estos subtemas',
  saveFeedback: 'Guardado en tus aficiones.', removeFeedback: 'Quitado de tus aficiones.',
};
export const copy = (s) => s.prefs.lang === 'es' ? es : en;

export function icon(name, size = 20) {
  const paths = {
    arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
    search: '<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',
    plus: '<path d="M12 5v14M5 12h14"/>',
    check: '<path d="m5 12 4 4L19 6"/>',
    network: '<circle cx="5" cy="17" r="3"/><circle cx="12" cy="5" r="3"/><circle cx="20" cy="16" r="3"/><path d="m6.5 14.5 4-7m3 0 5 6M8 17h9"/>',
    bookmark: '<path d="M6 4h12v17l-6-4-6 4z"/>',
  };
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.arrow}</svg>`;
}
