const { chromium, webkit } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const engine = process.argv.includes('--webkit') ? webkit : chromium;
  const browser = await engine.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  context.on('page', (page) => page.on('pageerror', (error) => errors.push(error.message)));
  const page = await context.newPage();
  const origin = process.env.AFICION_PREVIEW_URL || 'http://127.0.0.1:8877';
  try {
    await page.goto(origin + '/#node=model.gunpla');
    await page.locator('#nodeCompass [data-walk-to]').first().waitFor({ state: 'visible' });
    await page.waitForTimeout(500);
    await page.screenshot({ path: '/private/tmp/aficion-atlas-compass-desktop.png' });
    assert.equal(await page.locator('#detailBody .btn--primary').count(), 0, 'Saving must not be the primary call to action');
    const arrows = page.locator('#nodeCompass [data-walk-to]');
    assert.ok(await arrows.count() > 0 && await arrows.count() <= 12);
    const target = await arrows.first().getAttribute('data-walk-to');
    await arrows.first().hover();
    await page.screenshot({ path: '/private/tmp/aficion-atlas-preview-desktop.png' });
    assert.equal(await page.evaluate(async () => (await import('/js/state.js')).state.walk.preview?.to), target);
    await arrows.first().click();
    await page.waitForFunction((id) => document.getElementById('nodeCompass').dataset.anchor?.startsWith(id + ':'), target);
    await page.waitForTimeout(550);
    assert.deepEqual(await page.evaluate(async () => (await import('/js/state.js')).state.walk.path), ['model.gunpla', target]);
    assert.equal(await page.evaluate(async () => (await import('/js/state.js')).state.profile.n.length), 0, 'Following connections never saves a hobby');
    await page.screenshot({ path: '/private/tmp/aficion-atlas-trail-desktop.png' });
    await page.locator('[data-walk-back]').click();
    await page.waitForTimeout(400);
    assert.equal(await page.locator('#detailTitle').innerText(), 'Gunpla');
    await page.locator('.atlas-connection').first().focus();
    const rowTarget = await page.locator('.atlas-connection').first().getAttribute('data-walk-to');
    await page.keyboard.press('Enter');
    assert.equal(await page.evaluate(async () => (await import('/js/state.js')).state.selected), rowTarget);
    await page.waitForTimeout(450);
    await page.keyboard.press('Backspace');
    await page.waitForTimeout(450);
    assert.equal(await page.locator('#detailTitle').innerText(), 'Gunpla');
    const expected = await page.evaluate(async () => {
      const { state: s } = await import('/js/state.js');
      const { compassTargets } = await import('/js/atlas/traversal.js');
      return compassTargets(s.atlas, s.layout, s.selected)[0];
    });
    await page.locator('#atlasCanvas').focus();
    await page.keyboard.press('Arrow' + expected.id[0].toUpperCase() + expected.id.slice(1));
    assert.equal(await page.evaluate(async () => (await import('/js/state.js')).state.selected), expected.link.to);
    await page.waitForTimeout(450);
    await page.locator('#detailBody .atlas-save').click();
    assert.equal(await page.evaluate(async () => (await import('/js/state.js')).state.profile.n.length), 1);
    await page.locator('.atlas-detail-more summary').click();
    await page.locator('#detailBody .atlas-save').focus();
    await page.keyboard.press('Enter');
    assert.ok(await page.locator('.atlas-detail-more').evaluate((el) => el.open), 'Saving preserves expanded detail');
    assert.ok(await page.locator('#detailBody .atlas-save').evaluate((el) => el === document.activeElement), 'Saving preserves keyboard focus');
    await page.locator('.atlas-connection:visible').last().click();
    assert.equal(await page.locator('#side').evaluate((el) => el.scrollTop), 0, 'A new connection returns the sidebar to its title');
    await page.goto(origin + '/#node=model.gunpla');
    await page.reload();
    await page.locator('#nodeCompass button').first().waitFor({ state: 'visible' });
    await page.waitForTimeout(450);
    const dot = await page.evaluate(async () => {
      const { state: s } = await import('/js/state.js');
      const p = s.layout.pos.get(s.selected);
      return s.camera.toScreen(p.x, p.y);
    });
    const savedBeforeDrilling = await page.evaluate(async () => (await import('/js/state.js')).state.profile.n);
    await page.locator('#atlasCanvas').dblclick({ position: dot });
    await page.locator('#innerOverlay').waitFor({ state: 'visible' });
    assert.deepEqual(await page.evaluate(async () => (await import('/js/state.js')).state.profile.n), savedBeforeDrilling, 'Opening depth never saves a hobby');
    await page.locator('#innerClose').click();
    const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
    mobileContext.on('page', (p) => p.on('pageerror', (e) => errors.push(e.message)));
    const mobile = await mobileContext.newPage();
    await mobile.goto(origin + '/#node=model.gunpla');
    await mobile.locator('#nodeCompass [data-walk-to]').first().waitFor({ state: 'visible' });
    await mobile.screenshot({ path: '/private/tmp/aficion-atlas-compass-mobile.png' });
    const mobileArrow = mobile.locator('#nodeCompass [data-walk-to]').first();
    const mobileTarget = await mobileArrow.getAttribute('data-walk-to');
    await mobileArrow.tap();
    assert.equal(await mobile.evaluate(async () => (await import('/js/state.js')).state.selected), mobileTarget);
    assert.equal(await mobile.evaluate(async () => (await import('/js/state.js')).state.walk.motion.duration), 0);
    await mobile.locator('#stageCard [data-act="open-panel"]').tap();
    await mobile.locator('.atlas-connection').first().tap();
    assert.ok(!await mobile.locator('body').evaluate((el) => el.classList.contains('side-open')));
    await mobile.setViewportSize({ width: 320, height: 740 });
    await mobile.waitForFunction(async () => {
      const { state: s } = await import('/js/state.js');
      return s.camera.w === 320 && s.camera.h === document.getElementById('atlasCanvas').clientHeight;
    });
    assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await mobile.screenshot({ path: '/private/tmp/aficion-atlas-trail-mobile-320.png' });
    await mobile.goto(origin + '/?lang=es#node=model.gunpla');
    await mobile.locator('#nodeCompass button').first().waitFor({ state: 'visible' });
    assert.match(await mobile.locator('#nodeCompass button').first().getAttribute('aria-label'), /Seguir hasta/);
    assert.equal(await mobile.locator('#stageCard [data-act="open-panel"]').innerText(), 'Ver conexiones');
    await mobileContext.close();
    assert.deepEqual(errors, []);
    console.log('PASS: compass, previews, following real connections, trail/backtracking, keyboard, quiet saving, touch and reduced motion.');
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
