const { chromium, webkit } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await (process.argv.includes('--webkit') ? webkit : chromium).launch();
  const origin = process.env.AFICION_PREVIEW_URL || 'http://127.0.0.1:8877';
  const errors = [];
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  context.on('page', (page) => page.on('pageerror', (error) => errors.push(error.message)));
  const page = await context.newPage();
  const getWalk = () => page.evaluate(async () => (await import('/js/state.js')).state.walk);
  const openCoffee = async () => {
    await page.locator('#trailLibraryBtn').click();
    await page.locator('[data-trail-tab="suggested"]').click();
    await page.locator('.trail-row summary').first().click();
    await page.locator('[data-trail-open="coffee-meets-code"]').click();
  };
  try {
    await page.goto(origin + '/#atlas');
    await page.locator('#trailLibraryBtn').click();
    await page.locator('.trail-row').first().waitFor();
    assert.equal(await page.locator('.trail-row').count(), 6);
    await page.locator('[data-trail-tab="saved"]').click();
    assert.match(await page.locator('.trail-empty').innerText(), /Follow a few connections/);
    await page.keyboard.press('Escape');
    assert.ok(await page.locator('#trailLibraryBtn').evaluate((el) => el === document.activeElement), 'Modal close restores its trigger');
    await openCoffee();
    assert.deepEqual((await getWalk()).path, ['maker.arduino'], 'Opening a plan marks only the first stop as visited');
    assert.equal((await getWalk()).journey.step, 0);
    assert.equal(await page.locator('#journeyPanel [data-journey-back]').isDisabled(), true);
    await page.screenshot({ path: '/private/tmp/aficion-trails-desktop-overview.png' });
    await page.locator('#journeyPanel [data-journey-next]').focus();
    await page.keyboard.press('Enter');
    assert.deepEqual((await getWalk()).path, ['maker.arduino', 'core.electronics']);
    assert.equal((await getWalk()).journey.step, 1);
    assert.equal((await getWalk()).motion.duration, 0, 'Reduced motion skips line animation');
    assert.ok(await page.locator('#journeyPanel [data-journey-next]').evaluate((el) => el === document.activeElement));
    await page.locator('#journeyPanel [data-journey-back]').click();
    assert.equal((await getWalk()).journey.step, 0);
    assert.deepEqual((await getWalk()).path, ['maker.arduino']);
    // Saving the route explicitly saves the full plan, without marking hobbies.
    await page.locator('#journeyPanel [data-trail-save]').click();
    await page.locator('#trailName').fill('<b>Weekend coffee</b>');
    await page.locator('#trailForm [type="submit"]').click();
    assert.equal(await page.locator('.trail-row strong').innerText(), '<b>Weekend coffee</b>');
    assert.equal(await page.locator('.trail-row strong b').count(), 0, 'Route names render as text');
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('aficion:trails:v1')).routes[0].path.length), 4);
    await page.reload();
    await page.locator('#trailLibraryBtn').click();
    await page.locator('[data-trail-tab="saved"]').click();
    await page.locator('.trail-row summary').click();
    await page.locator('[data-trail-rename]').click();
    await page.locator('#trailName').fill('Weekend coffee');
    // Failed storage writes keep the form and the original saved route intact.
    await page.evaluate(() => { window.trailSetItem = Storage.prototype.setItem; Storage.prototype.setItem = function (key, value) { if (key === 'aficion:trails:v1') throw new Error('quota'); return window.trailSetItem.call(this, key, value); }; });
    await page.locator('#trailForm [type="submit"]').click();
    assert.match(await page.locator('#trailError').innerText(), /could not save/);
    assert.equal(await page.locator('#trailName').inputValue(), 'Weekend coffee');
    await page.evaluate(() => { Storage.prototype.setItem = window.trailSetItem; });
    await page.locator('#trailForm [type="submit"]').click();
    await page.locator('.trail-row summary').click();
    await page.locator('[data-trail-remove]').click();
    assert.equal(await page.locator('.trail-row').count(), 0);
    await page.locator('[data-trail-undo]').click();
    assert.equal(await page.locator('.trail-row strong').innerText(), 'Weekend coffee');
    await page.locator('.trail-row summary').click();
    await page.locator('[data-trail-open]').click();
    assert.equal((await getWalk()).journey.title, 'Weekend coffee');
    await page.locator('#journeyPanel [data-journey-next]').click();
    await page.locator('#journeyPanel [data-journey-next]').click();
    await page.locator('#journeyPanel [data-journey-next]').click();
    assert.equal((await getWalk()).journey.step, 3);
    assert.equal(await page.locator('#journeyPanel [data-journey-next]').count(), 0);
    assert.match(await page.locator('#journeyPanel').innerText(), /All stops explored/);
    assert.equal(await page.evaluate(async () => (await import('/js/state.js')).state.profile.n.length), 0, 'Guided routes never add hobbies');
    await page.locator('[data-walk-return="core.electronics"]').click();
    assert.equal((await getWalk()).journey.step, 1, 'Trail breadcrumbs keep the guide in sync');
    await page.locator('#detailBody [data-walk-to="core.soldering"]').click();
    assert.equal((await getWalk()).journey, null, 'An unplanned branch exits the guide');
    assert.deepEqual((await getWalk()).path, ['maker.arduino', 'core.electronics', 'core.soldering']);
    await page.locator('[data-trail-save]').filter({ visible: true }).first().click();
    await page.locator('#trailName').fill('My own branch');
    await page.locator('#trailForm [type="submit"]').click();
    assert.equal(await page.locator('.trail-row').count(), 2, 'An independently walked path can be named and saved');
    await page.keyboard.press('Escape');
    await openCoffee();
    await page.locator('#panelToggle').click();
    assert.ok(await page.locator('#journeyDock').isVisible(), 'Collapsing the sidebar keeps the guided controls accessible');
    await page.locator('#journeyDock [data-journey-next]').click();
    assert.equal((await getWalk()).journey.step, 1);
    await page.locator('#journeyDock [data-journey-close]').click();
    assert.equal((await getWalk()).journey, null);
    // Recoverable catalog errors do not prevent access to the saved library.
    const retry = await context.newPage();
    await retry.route('**/data/trails.json', (route) => route.fulfill({ status: 503, body: 'Unavailable' }));
    await retry.goto(origin + '/#atlas');
    await retry.locator('#trailLibraryBtn').click();
    await retry.locator('[data-trail-retry]').waitFor();
    await retry.unroute('**/data/trails.json');
    await retry.locator('[data-trail-retry]').click();
    await retry.locator('.trail-row').first().waitFor();
    assert.equal(await retry.locator('.trail-row').count(), 6);
    await retry.close();
    const mobile = await browser.newPage({ viewport: { width: 320, height: 740 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
    mobile.on('pageerror', (error) => errors.push(error.message));
    await mobile.goto(origin + '/?lang=es#atlas');
    await mobile.locator('#trailLibraryBtn').tap();
    await mobile.locator('.trail-row summary').first().tap();
    await mobile.screenshot({ path: '/private/tmp/aficion-trails-mobile-library.png' });
    await mobile.locator('[data-trail-open="coffee-meets-code"]').tap();
    assert.match(await mobile.locator('#journeyDock').innerText(), /Café y código/);
    assert.ok(await mobile.locator('#stageCard').isHidden());
    assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await mobile.screenshot({ path: '/private/tmp/aficion-trails-mobile-overview.png' });
    await mobile.locator('#journeyDock [data-journey-next]').tap();
    await mobile.screenshot({ path: '/private/tmp/aficion-trails-mobile-step.png' });
    await mobile.locator('#journeyDock [data-trail-save]').tap();
    await mobile.locator('#trailName').fill('Mi café');
    await mobile.locator('#trailForm [type="submit"]').tap();
    assert.equal(await mobile.locator('.trail-row strong').innerText(), 'Mi café');
    assert.match(await mobile.locator('[data-trail-tab="saved"]').innerText(), /Guardadas/);
    await mobile.locator('#trailModal .btn[data-modal-close]').tap();
    await mobile.locator('#journeyDock [data-journey-close]').tap();
    assert.ok(await mobile.locator('#stageCard').isVisible());
    assert.equal(await mobile.evaluate(async () => (await import('/js/state.js')).state.profile.n.length), 0);
    assert.deepEqual(errors, []);
    console.log('PASS: suggested trails, guided traversal, explicit saving, reload, rename, escaping, quota errors, remove/undo, side branches, collapsed sidebar, retry and 320px Spanish touch controls.');
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
